#!/usr/bin/env bash
# This script displays "Best School" 10 times and says "Hi" during the 9th
i="0"

while [ $i -lt 10 ]
do 
	if [ "$i" -eq "9" ]
	then
	echo "Hi"
	fi
	echo "Best School"
	i=$((i+1))
done
