#!/usr/bin/env bash
# Prints "Best School" 10x, "bad luck" the 4th, "good luck" the 8th
i="0"

while [ $i -lt 10 ]
do
	if [ "$i" -eq "3" ]
	then 
	echo "bad luck"
	elif [ "$i" -eq "7" ]
	then
	echo "good luck"
	else 
		echo "Best School"
        fi
	i=$((i+1))
done

